[package]
name = "riichinator"
version = "1.0.0"
entrypoint = "lib.typ"
authors = ["hemidemisemipresent (https://github.com/hemisemidemipresent)"]
license = "MIT"
description = "Riichi Mahjong hand and board state renderer."
repository = "https://github.com/pepengu/pepentation"
keywords = ["slides", "presentation", "beamer"]
categories = ["presentation"]
exclude = ["/screenshots/"]
